interfaces:
  basic_tictactoe:
    name: Basic Tic-Tac-Toe Solver
    description: Solve tic-tac-toe using Minimax and Alpha-Beta pruning
  tictactoe_cli:
    name: Tic-Tac-Toe CLI
    description: Command-line interface for the tic-tac-toe solver
    module_path: tiferet.contexts.cli
    class_name: CliContext
    attrs:
      cli_repo:
        module_path: tiferet.proxies.yaml.cli
        class_name: CliYamlProxy
        params:
          cli_config_file: app/configs/cli.yml
      cli_service:
        module_path: tiferet.handlers.cli
        class_name: CliHandler
